package:
  name: apsw
  version: "3.28.0.post1"

source:
  git_url: https://github.com/rogerbinns/apsw.git
  git_tag: 3.28.0-r1

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - icu
  run:
    - python
    - icu

test:
  imports:
    - apsw

