package:
  name: apsw
  version: "3.8.4.1.r1"

source:
  git_url: https://github.com/rogerbinns/apsw.git
  git_tag: 3.8.4.1-r1

build:
  number: 1

requirements:
  build:
    - sqlite
    - python
    - setuptools
  run:
    - sqlite
    - python

test:
  imports:
    - apsw

