package:
  name: apsw
  version: "3.7.13.r1"

source:
  git_url: https://github.com/rogerbinns/apsw.git
  git_tag: 3.7.13-r1

build:
  number: 1

requirements:
  build:
    - sqlite 3.7.13
    - python
    - setuptools
  run:
    - sqlite
    - python

test:
  imports:
    - apsw

