package:
  name: pysqlite
  version: "2.8.1"

source:
  fn: pysqlite-2.8.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pysqlite/pysqlite-2.8.1.tar.gz
  md5: 7a062cbd146eec630a575f099b0c2eaf

build:
  number: 0

requirements:
  build:
    - sqlite
    - python
    - setuptools
  run:
    - sqlite
    - python

test:
  imports:
    - pysqlite2

