name: build in conda

on: [push]

jobs:

  build:
    name: build in conda (${{ matrix.config.os }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            miniforge-url: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh"
          - os: macos-latest
            miniforge-url: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh"
          # exclude windows for now
          #- os: windows-latest
          #  miniforge-url: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup a miniforge distribution
      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: ${{ matrix.config.miniforge-url }}
          allow-softlinks: true
          show-channel-urls: true
          use-only-tar-bz2: true
      # Runs a single command using the runners shell
      - name: Run a one-line script
        shell: bash -l {0}
        run: conda info
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
